server:
    port: 8761
spring:
    datasource:
        url: jdbc:mysql://39.106.51.31:3306/fengwei?useUnicode=true&characterEncoding=utf8
        username: root
        password: 317812
        driver-class-name: com.mysql.jdbc.Driver
eureka:
    instance:
    hostname: localhost
client:
    registerWithEureka: false        # 是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故而设为false
    fetchRegistry: false             # 表示是否从Eureka Sever获取注册信息，默认为true。因为这个一个单节点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false
    serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/      # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。